export const FETCH_MATCHERINO_PENDING = 'FETCH_MATCHERINO_PENDING'
export const FETCH_MATCHERINO_FULFILLED = 'FETCH_MATCHERINO_FULFILLED'
export const FETCH_MATCHERINO_REJECTED = 'FETCH_MATCHERINO_REJECTED'